### PR TITLE
Added support to multiple payloads at once

### PR DESCRIPTION
**Pull request by unnamedd**

### CODE REVIEW

**Comment by unnamedd** [comment]
hey @blommegard, do you agree with this PR ? I believe that the option to send multiple payloads at once is a good feature, but of course, it is good to me, maybe isn't good to another one.

Do you have any correction to suggest ?

**Comment by blommegard** [comment]
The main goal of Knuff is to be a debug tool for APNS and not really to use it in "production".
Just curious, what are you testing out when sending multiple payloads?

I realise as well that this can be merged and Knuff will still work just as before, but it will add some new code paths that seems a little bitt unnecessary for a debug tool.

**Comment by unnamedd** [comment]
Last year, I worked at a company and there, I implemented push notification in some apps, and these apps received different payloads. 
Changing these payloads every time I needed to test new kind of notification was really boring. I made this changes on Knuff to help me send multiple payloads with no need to open many instances of Knuff.

The main goal wasn't send a large amount of payloads, as companies like Urban Airship and others does in production, it was just to test a few different payloads for the same app in debugging time.

This was just a first contribution, I got some other ideas to help to improve the Knuff as a tool. If you'd like to, we could discuss about it later.

**Comment by blommegard** [comment]
Ah, I get the idea, but I would like the payload to represent something that is valid for APNS as well.
We should absolutely try to figure out another way to easily send multiple variants of a payload that both works with your workflow and my goals of Knuff.

**Comment by unnamedd** [comment]
If we implement some kind of history (as you propose on issue #65), I'm sure that this PR won't be needed anymore!

Thank you for you response! :)

**Pull request closed without merging**
