### PR TITLE
APNS push type (iOS 13, watchOS 6)

### PR DESCRIPTION
**Pull request by ricardopereira**
Related with #85.

### Changes:
- Support for [APNS push type](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns).

apns-push-type | (Required for watchOS 6 and later; recommended for macOS, iOS, tvOS, and iPadOS) The value of this header must accurately reflect the contents of your notification’s payload. If there is a mismatch, or if the header is missing on required systems, APNs may return an error, delay the delivery of the notification, or drop it altogether.
-- | --

- Update project to Xcode 11.

#### Screenshot
Screenshot 2019-10-25 at 16 51 07

### CODE REVIEW

**Comment by blommegard** [comment]
Hi, I am so sorry that I have ignored this PR. Thanks for all the work, this looks great.
One question, why change the submodule url from `git@github.com:shysaur/Fragaria.git` to ´https://github.com/shysaur/Fragaria.git´?

**Comment by ricardopereira** [comment]
HI @blommegard 🤚, I changed the submodule url because of this:

4d7b76f (Submodule should use HTTPS instead of SSH to simplify contributions)
```
Solves this issue:

➜  Knuff git:(master) ✗ git submodule update --init --recursive
Submodule 'Vendor/Fragaria' (git@github.com:shysaur/Fragaria.git) registered for path 'Vendor/Fragaria'
Cloning into '/Users/<redacted>/Repositories/Knuff/Vendor/Fragaria'...
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:shysaur/Fragaria.git' into submodule path '/Users/<redacted>/Repositories/Knuff/Vendor/Fragaria' failed
Failed to clone 'Vendor/Fragaria'. Retry scheduled
Cloning into '/Users/<redacted>/Repositories/Knuff/Vendor/Fragaria'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:shysaur/Fragaria.git' into submodule path '/Users/<redacted>/Repositories/Knuff/Vendor/Fragaria' failed
Failed to clone 'Vendor/Fragaria' a second time, aborting
```

**Comment by anhar** [comment]
@ricardopereira I'm running the ios13 branch from your fork for testing purposes and I found one issue with the syntax highlighting for the JSON payload. It's not showing the following characters: `: { } ,`

See the attached images below:
knuff-syntax-highlighting-bug1
knuff-syntax-highlighting-bug2

**Comment by blommegard** [comment]
@anhar Same in dark and light mode?

Mu guessing is that it is Fragaria related, maybe we should just ditch that in favour for a plain text view.

**Comment by anhar** [comment]
@blommegard Yeah you're right it's only dark mode related. If you run it in light mode it's fine:

image

**Comment by anhar** [comment]
I'll create another issue for that though @blommegard. The rest seem to be working fine.

**Comment by brunomunizaf** [comment]
+1 I need this release so bad...

**Comment by Benny-iPhone** [comment]
Can you share a zip download so I won't have to struggle with project compiling?

**Comment by ricardopereira** [comment]
@blommegard Can I help on something to release a new version?

**Comment by blommegard** [comment]
I will merge this PR and create a new release, thanks for all the work @ricardopereira, and sorry for my slowness to get this done.

**Comment by ricardopereira** [comment]
It's ok. Thank you!

**Comment by blommegard** [comment]
[1.3](https://github.com/KnuffApp/Knuff/releases/tag/v1.3) is now released, please see if it works as expected, I will then publish the sparkle update.

**Comment by blommegard** [comment]
[1.3](https://github.com/KnuffApp/Knuff/releases/tag/v1.3) is now released on Sparkle, thanks again @ricardopereira!

**Pull request merged**
