### PR TITLE
Move the preview to GitHub CDN

### PR DESCRIPTION
**Pull request by vinkla**
Instead of keeping the screenshot within the code we can utilize GitHub's CDN. Will make the repository file listing look cleaner :)

### CODE REVIEW

**Comment by blommegard** [comment]
How do you add assets to the CDN?

**Comment by vinkla** [comment]
You create a new issue and drag-n-drop the image you want into the field. GitHub will then provide you with a link once it is uploaded.

**Comment by vinkla** [comment]
Here is a link to the docs https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by blommegard** [comment]
Perfect, thanks! :)

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
