### PR TITLE
Add support for apns-collapse-id

### PR DESCRIPTION
**Pull request by onevcat**
As mentioned in #51, I added support for apns-collapse-id.

For back compatibility, I added a new method containing `collapseId` as a parameter in `SBAPNS`, while keeping the original one. It should not be necessary. If you'd like, I could remove it with another commit.

### CODE REVIEW

**Comment by blommegard** [comment]
Thanks for the PR!
I actually had a look at this yesterday, it would be great to repopulate the field after a successful push have been made.

What do you think about that?

**Comment by onevcat** [comment]
@blommegard Wow, it will be cool to have a result box (or panel, or something could visually feedback) to show the result. 

I think it's a good idea, but I am not sure in which way you want it. So I am afraid it's hard for me to help on it.

**Comment by ynot16** [comment]
em....I wonder if it has supported the apns-collapse-id key?

**Comment by ajaybeniwal** [comment]
Any plans to merge this branch because i  also waiting for apns-collapse-id  key for request identification

**Comment by DavidSpringhetti** [comment]
I am also waiting for apns-collapse-id to keep from spamming my clients notifications when the same conversation is updated multiple times in a short period of time. Thanks.

**Comment by aman46** [comment]
can apns-collapse-id merge both local and remote notification of same id ?

**Comment by aman46** [comment]
is collapse id can merge local and remote notification of same id ?

**Comment by blommegard** [comment]
This feature is now merged! https://github.com/KnuffApp/Knuff/pull/70

**Comment by blommegard** [comment]
@aman46 That I don't know to be honest. :)

**Pull request closed without merging**
